name: autovi
publish_to: 'none'
description: Auto horizontal video flipper for iPhone and Android.
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^11.0.2
  ffmpeg_kit_flutter_new: ^4.5.1
  gallery_saver_plus: ^3.2.9
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
